AnimalGame/Models/Animal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Feature { get; set; }
        public string Sound { get; set; }
    }
}

AnimalGame/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AnimalGame.Models;

namespace AnimalGame.Controllers
{
    public class AnimalController : Controller
    {
        private AnimalGameDataEntities db = new AnimalGameDataEntities();

        // GET: Animals
        public ActionResult Index()
        {
            return View(db.Animals.ToList());
        }

        // GET: Animals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animals.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }

        // GET: Animals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Animals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Color,Feature,Sound")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                db.Animals.Add(animal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(animal);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AnimalGame/Controllers/QuestionController.cs
using AnimalGame.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnimalGame.Controllers
{
    public class QuestionController : Controller
    {
        // GET: Question

        private AnimalGameDataEntities db = new AnimalGameDataEntities();

        public ActionResult Index()
        {
            var distinctColors = (from col in db.Animals
                                 select col.Color).Distinct();
            
            var distinctFeatures= (from col in db.Animals
                                  select col.Feature).Distinct();

            var distinctSounds = (from col in db.Animals
                                   select col.Sound).Distinct();

            ViewBag.Colors = distinctColors;
            ViewBag.Features = distinctFeatures;
            ViewBag.Sounds = distinctSounds;

            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            try
            {
                var selectedColor = form["AnimalColor"].ToString();

                var selectedFeature = form["AnimalFeature"].ToString();

                var selectedSound = form["AnimalSound"].ToString();

                string chosenAnimal = (from anim in db.Animals.Where(x => x.Color == selectedColor && x.Sound == selectedSound && x.Feature == selectedFeature)
                                       select anim.Name).FirstOrDefault();



                if (string.IsNullOrEmpty(chosenAnimal))
                    ViewBag.Message = "No matching animal found";
                else
                    ViewBag.Message = "You thought of animal " + chosenAnimal.ToString();
            }
            catch (NullReferenceException ex)
            {
                ViewBag.Message = "No matching animal found";

            }
            catch(Exception ex)
            {
                ViewBag.Message = "Error in the application. please try again.";
            }
             return View("Result");
            
        }
    }
}

AnimalGame/Views/Animal/Create.cshtml
@model AnimalGame.Models.Animal

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="form-horizontal">
            <h4>Animal</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Feature, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Feature, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Feature, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sound, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sound, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sound, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AnimalGame/Views/Animal/Index.cshtml
@model IEnumerable<AnimalGame.Models.Animal>

@{
    ViewBag.Title = "Kids-Guess The Animal Game";
}
<div>
    <h4>Kids, here is the list of animals.Please choose one and keep it in your mind. Press <b>Start</b> to start the game.</h4>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <br />
    <ul>

        @foreach (var item in Model)
        {
            <li>
                @Html.DisplayFor(modelItem => item.Name)

            </li>
        }
    </ul>
    <br />

    <p>@Html.ActionLink("Start", "Index", "Question", null, htmlAttributes: new { @class = "btn btn-default" })</p>

</div>