AnimalGame/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AnimalGame.Models;

namespace AnimalGame.Controllers
{
    public class AnimalController : Controller
    {
        private AnimalGameDataEntities db = new AnimalGameDataEntities();

        // GET: Animals
        public ActionResult Index()
        {
            return View(db.Animals.ToList());
        }

        // GET: Animals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Animal animal = db.Animals.Find(id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }

        // GET: Animals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Animals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Color,Feature,Sound")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                db.Animals.Add(animal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(animal);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AnimalGame/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnimalGame.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }       

        public ActionResult List()
        {
            return View();
        }
    }
}

AnimalGame/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Kids-Guess The Animal Game";
}

<div class="jumbotron">
    <h1>Kids-Guess The Animal Game</h1>
   <p class="lead">This is a small game for kids to answer some question based on the animal that they have thought and we will predict what the animal was.</p>
    
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            This is a small game for kids to answer some question based on the animal that have thought and we will predict what the animal was. Below is the list of Animals and kids can choose any one of them and keep in there mind. Press OK and answer few questions on the next screen based on what they do, color and there features.
            After they have answerd the questions , the system will let you know what animal you chose. Isn't it fun. Give it a try.
        </p>
        <p>@Html.ActionLink("Try it!","Index","Animal",null, htmlAttributes: new { @class = "btn btn-default" })</p>
    </div>
    
</div>